### ISSUE TITLE
No Posts found message on clicking "Buy" button

### ISSUE THREAD

**Issue by fatmaelazab** [SEGUC17/hackslash#73]
1-Severity:
 
Low

2-Reported By:
 
Fatma Elazab

3-Description:

The user gets "no posts found" message when he clicks on "Buy" button although after a sec the page reloads with the data "Latest Posts".

4-Steps to reproduce the issue:

 1)Open the home page
 2)Click on "Buy" button/ or click on "Buy a pet" 

5-Expected result:

When the user clicks on buy , he should not get "No posts found" first and then see the posts.He should see them automatically after clicking on buy.

**Comment by mohamedazab** [comment]
fixed
