### ISSUE TITLE
Register with invalid email 

### ISSUE THREAD

**Issue by Mirran610** [SEGUC17/hackslash#79]
1-Severity: medium 

2-Reported By: Miran Ashraf - Mariam Amin - Youmna Khaliffa 

3-Description:
The user can enter any email even if it is not a real one, it doesn't check if it is a valid email address. Having a valid and real email address is important  as you should verify your account through the email and it can be a way of communication then.

4-Steps to reproduce the issue:
1.Open the home page
2.Click the "Register" button
3.Register with any email like "aa@g.com" 
4. click "join now", it will accept it

5-Expected result:
When the user clicks on "join now" there must be an error message given to the user if the the email id not real/valid is invalid .

**Comment by youmnakhalifa** [comment]
1) Severity: high

2) Reported by: Youmna Khalifa

3) The registration process is successful despite registering with an invalid email. When attempting to sign in with the following email: youmna.khalifaa@gmail.com, Google displays a message saying "Sorry, Google doesn't seem to recognize that email.". I have "completed" the process of registration using this email and the following message "verification mail sent" was displayed despite it being an invalid email.

4)
a) Click the registration button found on the homepage
b) Make sure all required fields are filled
c) Use the email provided above or any non-existing email
d) Registration is successful despite using an invalid email address.

5) Expected result: An error message should be displayed. Something like "This is an invalid email.".
