### ISSUE TITLE
Error message when logging in/viewing profile

### ISSUE THREAD

**Issue by youmnakhalifa** [SEGUC17/hackslash#88]
1) Severity: medium

2) Reported by: Youmna Khalifa

3) When logged in, a message saying "This user does not exist" is quickly then replaced by posts the user has posted. The same thing happens when viewing the user's profile. An error message is displayed for no reason.

4)
a) Click the log in button found on the homepage
b) Make sure all required fields are filled and click the log in button
c) The message will be displayed before the posts are displayed
d) Click My Profile button found at the top of the page
e) The same message is displayed before the profile loads

5) Expected result: The profile and posts should be loaded without an error message at the beginning.

**Comment by mohamedazab** [comment]
fixed
